version: 2

updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/New_York
    open-pull-requests-limit: 5
    groups:
      android-production:
        dependency-type: production
        update-types:
          - minor
          - patch
      android-development:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:15"
      timezone: America/New_York
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
